animal:
	g++ Animal.cpp ../FarmProduct.cpp ../Product.cpp ../CamelMilk.cpp ../CowMilk.cpp ../DuckEgg.cpp ../ChickenEgg.cpp ../HorseMeat.cpp ../GoatMeat.cpp ../Camel.cpp ../Cow.cpp ../Duck.cpp ../Chicken.cpp ../Horse.cpp ../Goat.cpp ../FarmAnimal.cpp ../Renderable.cpp -o 5

player:
	g++ Player.cpp ../Player.cpp ../Product.cpp ../FarmProduct.cpp ../SideProduct.cpp ../CamelMilk.cpp ../Pancake.cpp ../HorseMeat.cpp ../DuckEgg.cpp -o 5

Main:
	g++ Main.cpp ../Barn.cpp ../Camel.cpp ../CamelMilk.cpp ../Cell.cpp ../Chicken.cpp ../ChickenEgg.cpp ../Coop.cpp ../Cow.cpp ../CowMilk.cpp ../Duck.cpp ../DuckEgg.cpp ../Facility.cpp ../FarmAnimal.cpp ../FarmProduct.cpp ../Game.cpp ../Goat.cpp ../GoatMeat.cpp ../Grassland.cpp ../Horse.cpp ../HorseMeat.cpp ../Land.cpp ../Mixer.cpp ../Omelette.cpp ../Pancake.cpp ../Player.cpp ../Product.cpp ../Renderable.cpp ../Sausage.cpp ../SideProduct.cpp ../Truck.cpp ../Well.cpp -o main

cell:
	g++ Cell.cpp ../Cell.cpp ../Land.cpp ../Facility.cpp ../Truck.cpp ../Well.cpp ../Mixer.cpp ../Barn.cpp ../Grassland.cpp ../Coop.cpp ../Renderable.cpp ../SideProduct.cpp ../Sausage.cpp ../Pancake.cpp ../Omelette.cpp ../Product.cpp ../Player.cpp -o m