animal:
	g++ Animal.cpp ../FarmProduct.cpp ../Product.cpp ../CamelMilk.cpp ../CowMilk.cpp ../DuckEgg.cpp ../ChickenEgg.cpp ../HorseMeat.cpp ../GoatMeat.cpp ../Camel.cpp ../Cow.cpp ../Duck.cpp ../Chicken.cpp ../Horse.cpp ../Goat.cpp ../FarmAnimal.cpp ../Renderable.cpp -o 5
